Fixes #17878: All plugins are disabled after a minor upgrade
Normation/rudder-packages pull request #2368
Opened 2020-10-08 10:13 UTC by VinceMacBuche

https://issues.rudder.io/issues/17878

2020-10-08 12:58 UTC, VinceMacBuche commented
PR updated with a new commit

2020-10-21 09:24 UTC, ncharles commented on rudder-webapp/SOURCES/rudder-upgrade
> +  rudder package licenses
could you add a STEP

2020-10-21 09:24 UTC, ncharles commented on rudder-webapp/SOURCES/rudder-upgrade
> -  rudder package rudder-postupgrade
STEP="Upgrade all plugins if necessary"

2020-10-21 09:47 UTC, ncharles requested changes
It is necessary to had a STEP name for error handling

2020-10-21 09:57 UTC, VinceMacBuche commented
PR updated with a new commit

2020-10-21 10:00 UTC, amousset commented on rudder-webapp/SOURCES/rudder-upgrade
> +  rudder package licenses || true
an `if rudder package test-connection` would allow displaying error messages only when needed (i.e. connection works but plugin management fails)

2020-10-21 10:30 UTC, VinceMacBuche commented
PR updated with a new commit

2020-10-21 10:32 UTC, amousset commented on rudder-webapp/SOURCES/rudder-upgrade
> +    rudder package licenses || true
no need for licences command anymore

2020-10-21 10:44 UTC, VinceMacBuche commented
PR updated with a new commit

2020-10-21 10:45 UTC, amousset approved these changes

2020-10-22 09:55 UTC, Normation-Quality-Assistant commented
This PR is not mergeable to upper versions.
Since it is "Ready for merge" you must merge it by yourself using the following command:
`rudder-dev merge https://github.com/Normation/rudder-packages/pull/2368`
-- Your faithful QA
Kant merge: "Science is organized knowledge. Wisdom is organized life."
 (https://ci.normation.com/jenkins/job/merge-accepted-pr/31394/console)

2020-10-22 10:09 UTC, fanf commented
OK, squash merging this PR

2020-10-22 10:09 UTC, merged