Fixes #20232: Git error on webapp posting: missing user email
Normation/rudder-packages pull request #2541
Opened 2021-11-03 14:41 UTC by amousset

https://issues.rudder.io/issues/20232

2021-11-05 14:17 UTC, ncharles requested changes
you cannot git config user.name if you are not in a git repository

2021-11-05 14:17 UTC, ncharles commented on rudder-webapp/SOURCES/rudder-webapp-postinst
> +  git init --shared=group >> ${LOG_FILE}
this will fail with a 
`fatal: not in a git directory

2021-11-05 14:20 UTC, amousset commented
PR updated with a new commit

2021-11-05 14:22 UTC, amousset commented
PR updated with a new commit

2021-11-08 10:50 UTC, ncharles approved these changes

2021-11-08 10:51 UTC, Normation-Quality-Assistant commented
OK, squash merging this PR

2021-11-08 10:51 UTC, merged