Fixes #23931: Make the rudder-agent package depends of python
Normation/rudder-packages pull request #2844
Opened 2023-12-18 15:35 UTC by Fdall

https://issues.rudder.io/issues/23931

2023-12-18 16:05 UTC, peckpeck requested changes

2023-12-18 16:05 UTC, peckpeck commented on rudder-agent/SPECS/rudder-agent.spec
> +Requires: python unless python3
This should be OR instead of unless

2023-12-18 16:05 UTC, peckpeck commented on rudder-agent/SPECS/rudder-agent.spec
> +%define with_perl false
with python ?

2023-12-18 16:21 UTC, Fdall commented
PR updated with a new commit

2023-12-18 17:29 UTC, peckpeck commented on rudder-agent/SPECS/rudder-agent.spec
> +%define with_openssl false
why ?

2023-12-18 17:29 UTC, peckpeck commented on rudder-agent/SPECS/rudder-agent.spec
> +%if "%{requires_python}" == "true" && 0%{?rhel} >= 9
why do you need a variable since the knowledge of which distribution needs what is embedded here ? This is duplicate

2023-12-19 09:11 UTC, Fdall commented
PR updated with a new commit

2023-12-19 09:52 UTC, Fdall commented
PR updated with a new commit

2023-12-19 10:10 UTC, Fdall commented
PR updated with a new commit

2023-12-19 10:15 UTC, peckpeck approved these changes

2023-12-19 10:16 UTC, Normation-Quality-Assistant commented
OK, squash merging this PR

2023-12-19 10:16 UTC, merged